name: Lint

on:
  push:
    branches:
      - master
      - production
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'zhuxiangxiao'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            src/package-lock.json

      - name: npm run lint
        run: |
          cd src
          npm ci
          npm run lint
